services:
    backend:
        build: .
        container_name: backend
        ports:
            - 9000:9000
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysql:3306/studentuure",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "test",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
              }'
        depends_on:
            - mysql
        command: ["sh", "-c", "java $JAVA_OPTS -jar studenture-backend.jar"]
    mysql:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: studentuure
        ports:
            - 3307:3306
        volumes:
            - "./../database/studentuure.sql:/docker-entrypoint-initdb.d/1.sql"
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: